### ISSUE TITLE
วาร์ปกลับเมืองเองรัวๆ

### ISSUE THREAD

**Issue by ImmaGOOD** [korakot14/NightCrows-Simple-Detect-when-get-Attack#2]
ขนาดหน้าต่างเกม Full screen 1920 x 1080 บอทวาร์ปกลับเมืองรัวๆจนใบวาร์ปหมด ทั้งๆที่ไม่โดนตี

**Comment by VichianCreater** [comment]
ลองโหลดเวอร์ชั้นใหม่ดูครับ แก้เปลี่ยนจากเช็คทั้งหน้าจอเป็นเช็คเฉพาะมุมขวาล่างของหน้าต่างเกมส์ แต่ถ้าเปิด "threshold": 0.7 บางทียังตรวจจับมั่วอยู่ครับถ้าเปิดกระเป๋า แต่เท่าที่ทดสอบมาถ้าไม่เปิดกระเป๋าจะไม่มั่วแล้วครับ 

ถ้ายังเจอปัญหาอยู่แจ้งเข้ามาได้เลยครับ
